// <auto-generated />
namespace Task5_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addflowerrequirednamefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addflowerrequirednamefield));
        
        string IMigrationMetadata.Id
        {
            get { return "202004191542375_add flower required name field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
