// <auto-generated />
namespace Task5_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class add_isoptional_param : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isoptional_param));
        
        string IMigrationMetadata.Id
        {
            get { return "202004222303223_add_isoptional_param"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
